build_tools:
  - gcc
  - g++
  - make
  - cmake
dlep_deps:
  - libreadline-dev
  - libxml2-dev
  - libxml2-utils
  - libprotobuf-dev
  - protobuf-compiler
  - libboost-all-dev
  - doxygen
  - graphviz
