build_tools:
  - centos-release-scl
  - devtoolset-3-gcc
  - devtoolset-3-gcc-c++
  - make
  - cmake
dlep_deps:
  - readline-devel
  - libxml2-devel
  - protobuf-devel
  - protobuf-compiler
  - boost148-devel
  - doxygen
  - graphviz
build_env:
  CC: /opt/rh/devtoolset-3/root/usr/bin/gcc
  CXX: /opt/rh/devtoolset-3/root/usr/bin/g++
  BOOST_INCLUDEDIR: /usr/include/boost148/
  BOOST_LIBRARYDIR: /usr/lib64/boost148/
