---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: all
  require_chef_for_busser: false
  additional_copy_path: tasks
  ansible_verbose: true
  ansible_verbosity: 3

transport:
  name: ssh
  max_ssh_sessions: 2

platforms:
  - name: centos/7
  - name: centos/6
  - name: fedora/28-cloud-base
    driver:
     customize:
       memory: 1024 
  - name: fedora/27-cloud-base
    driver:
     customize:
       memory: 1024 
  - name: ubuntu/bionic64
  - name: ubuntu/xenial64
  - name: ubuntu/trusty64
    driver:
     customize:
       memory: 1024 
  - name: debian/stretch64
  - name: debian/jessie64
  - name: opensuse/openSUSE-42.3-x86_64
    provisioner:
      python_sles_repo: http://download.opensuse.org/repositories/devel:/languages:/python/openSUSE_Leap_42.3/devel:languages:python.repo
      ansible_sles_repo: http://download.opensuse.org/repositories/systemsmanagement/openSUSE_Leap_42.3/systemsmanagement.repo
  - name: generic/alpine37
    driver:
      vm_hostname: false
  - name: generic/arch
    provisioner:
      custom_pre_install_command: |
         sudo /usr/bin/pacman -Syyu --noconfirm && \
         sudo /usr/bin/pacman -S --verbose --noconfirm ansible
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'
  - name: generic/freebsd11
    provisioner:
      custom_pre_install_command: sudo pkg install -y ansible
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'
  - name: generic/openbsd6
    provisioner:
      ansible_extra_flags: -e 'ansible_python_interpreter="/usr/bin/env python2.7"'

suites:
  - name: default

verifier:
#  name: shell
#  remote_exec: true
#  command: env


